site_name: Programação Orientada a Objetos (POO) com Python
site_url: https://uadson.github.io/poo/
site_author: Uadson Feitosa

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - header.autohide
    - content.code.copy
  palette:
    scheme: default
    primary: teal
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    link: https://github.com/uadson/poo

nav:
  - Início: index.md
  - Conteúdo:
      - Parte 1:
          - Classes e Objetos: content/modules/1/classes_e_objetos.md
          - Encapsulamento: content/modules/1/encapsulamento.md
          - Herança: content/modules/1/heranca.md
          - Polimorfismo: content/modules/1/polimorfismo.md
          - Composição e Agregação: content/modules/1/composicao_relacao.md
          - Exemplo: content/modules/1/exemplo.md
      - Parte 2:
          - SOLID: content/modules/2/solid.md
  - Sobre: about.md

copyright: Copyright &copy; 2025 Uadson Feitosa | Licença MIT.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uadson
      name: Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/uadsonfeitosa
      name: LinkedIn

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings:
      default_handler: python

repo_url: https://github.com/uadson/poo
repo_name: uadson/poo
