site_name: Mini curso de programação orientada a objetos
nav:
  - Home: index.md
  - Seções:
      - Classes e Objetos: classes_e_objetos.md
      - Encapsulamento: encapsulamento.md
      - Herança: heranca.md
      - Polimorfismo: polimorfismo.md
      - Composicão e Agregação: composicao_relacao.md
      - SOLID: solid.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
