site_name: Programação Orientada a Objetos (POO) com Python
site_url: https://uadson.github.io/poo/
site_author: Uadson Feitosa

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - header.autohide
    - content.code.copy
  palette:
    scheme: default
    primary: teal
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    link: https://github.com/uadson/poo/

nav:
  - Início: index.md
  - Conteúdo:
      - Parte 1:
          - Classes e Objetos: content/modules/1/classes_e_objetos.md
          - Encapsulamento: content/modules/1/encapsulamento.md
          - Herança: content/modules/1/heranca.md
          - Polimorfismo: content/modules/1/polimorfismo.md
          - Composição e Agregação: content/modules/1/composicao_relacao.md
          - Exemplo: content/modules/1/exemplo.md
      - Parte 2:
          - SOLID: content/modules/2/solid.md
          - Exemplo:
              - Projeto Banco: content/modules/2/example/project/projeto.md
              - banco:
                  - dominio:
                      - entidades: content/modules/2/example/banco/dominio/entidades.md
                      - interfaces: content/modules/2/example/banco/dominio/interfaces.md
                  - infra:
                      - repositorios: content/modules/2/example/banco/infra/repo_memoria.md
                  - CLI ou Interface Gráfica: content/modules/2/example/banco/cli.md
      - Parte 3:
          - Design Patterns: content/modules/3/design_patterns.md
          - Exemplo:
              - Resumo: content/modules/3/example/summary.md
              - Singleton: content/modules/3/example/singleton.md
              - Factory: content/modules/3/example/factory.md
              - Strategy: content/modules/3/example/strategy.md
              - Observer: content/modules/3/example/observer.md
              - Decorator: content/modules/3/example/decorator.md
              - Adapter: content/modules/3/example/adapter.md

  - Sobre: about.md

copyright: Copyright &copy; 2025 Uadson Feitosa | Licença MIT.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uadson
      name: Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/uadsonfeitosa
      name: LinkedIn

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings:
      default_handler: python

repo_url: https://github.com/uadson/poo/
repo_name: uadson/poo
